version: '3.2'

services:
  srsue:
    hostname: srsue
    container_name: srsue01
    build: .
    ports:
       - "2004:2004/tcp"
    networks:
      ue01:
        ipv4_address: 10.8.1.4
    volumes:
     - type: bind
       source: "./file/"
       target: "/root/file/"
    tty: true
    stdin_open: true
    privileged: true

  srsenb:
    hostname: srsenb
    container_name: srsenb01
    build: .
    ports:
       - "2002:2002/tcp"
    command: >
       sh -c "route add -host 10.7.1.2 eth0; /bin/bash"
    networks:
      ran01:
        ipv4_address: 10.6.1.2
      ue01:
        ipv4_address: 10.8.1.2
    volumes:
     - type: bind
       source: "./file/"
       target: "/root/file/"
    tty: true
    stdin_open: true
    privileged: true

  srsepc:
    hostname: srsepc
    container_name: srsepc01
    build: .
    ports:
       - "2003:2003/tcp"
    command: >
       sh -c "route add -host 10.6.1.2 eth0 &&
              route del default &&
              route add default gw 10.9.1.1 &&
              iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE; /bin/bash"
    networks:
      core01:
        ipv4_address: 10.7.1.2
      sgi01:
        ipv4_address: 10.9.1.2
      sgi02:
        ipv4_address: 10.9.2.2
    volumes:
     - type: bind
       source: "./file/"
       target: "/root/file/"
    tty: true
    stdin_open: true
    privileged: true

  mec:
    hostname: mec
    container_name: mec01
    build: .
    command: >
       sh -c "arp -i eth0 -s 10.6.1.2 02:42:0a:07:01:03 pub &&
              arp -i eth1 -s 10.7.1.2 02:42:0a:06:01:03 pub &&
              arp -i eth2 -s 10.5.2.3 02:42:0a:09:02:03 pub &&
              route add -host 10.7.1.2 eth0 &&
              route add -host 10.6.1.2 eth1 &&
              iptables -I FORWARD -j NFQUEUE --queue-num 0 ; /bin/bash"
    networks:
     service01:
       ipv4_address: 10.5.1.3
     core01:
       ipv4_address: 10.7.1.3
     ran01:
       ipv4_address: 10.6.1.3
    volumes:
     - type: bind
       source: "./file/"
       target: "/root/file/"
    tty: true
    stdin_open: true
    privileged: true

  service:
    hostname: service
    container_name: service01
    build: .
    command: >
       sh -c "route del default &&
              route add default gw 10.5.1.3 ; /bin/bash"
    networks:
     service01:
       ipv4_address: 10.5.1.2
    volumes:
     - type: bind
       source: "./file/"
       target: "/root/file/"
    tty: true
    stdin_open: true
    privileged: true

networks:
   service01:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.5.1.0/24
   ran01:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.6.1.0/24
   core01:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.7.1.0/24
   ue01:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.8.1.0/24
   sgi01:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.9.1.0/24
   sgi02:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 10.9.2.0/24
